version: '3.7'
services:
  mysql:
    image: mysql:8.0.36
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  postgres:
    image: postgres:14.10-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node:
    image: 'node:current-alpine'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./gate-emulator:/home/node/app
    ports:
      - '9999:9999'
    command: 'npm start'